#include "Core\CaptureRegion.au3"

#include "Functions\autoMergeDice.au3"
#include "Functions\checkMainScreen.au3"
#include "Functions\checkBattleScreen.au3"
#include "Functions\checkQuickMatch.au3"
#include "Functions\checkAds.au3"
#include "Functions\viewAds.au3"
#include "Functions\startNewGame.au3"
#include "Functions\autoPlayGame.au3"
#include "Functions\waitForAds.au3"
#include "Functions\checkDisconnect.au3"
#include "Functions\checkTimeout.au3"
#include "Functions\openGiftCard.au3"
#include "Functions\capturePosition.au3"