#include "Functions\checkMainScreen.au3"
#include "Functions\checkBattleScreen.au3"
#include "Functions\checkQuickMatch.au3"
#include "Functions\checkAds.au3"
#include "Functions\viewAds.au3"
#include "Functions\startNewGame.au3"
#include "Functions\autoPlayGame.au3"
#include "Functions\waitForAds.au3"